# Generated by Django 3.0.5 on 2020-05-08 11:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_web', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857),
        ),
        migrations.AlterField(
            model_name='campingarea',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857),
        ),
        migrations.AlterField(
            model_name='location',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857),
        ),
        migrations.AlterField(
            model_name='swimmingpool',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857),
        ),
        migrations.AlterField(
            model_name='tree',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=3857),
        ),
    ]
