# Generated by Django 3.0.5 on 2020-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_web', '0004_auto_20200508_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='bookings',
            field=models.ManyToManyField(to='geo_web.Booking'),
        ),
    ]
