# Generated by Django 3.0.5 on 2020-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('geo_web', '0007_remove_booking_busy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterField(
            model_name='location',
            name='bookings',
            field=models.ManyToManyField(to='booking.Booking'),
        ),
    ]
