# Generated by Django 3.0.5 on 2020-06-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_web', '0008_auto_20200531_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCampingArea',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geo_web.campingarea',),
        ),
    ]
