# Generated by Django 3.0.5 on 2020-06-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_web', '0009_mycampingarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myCampingArea',
        ),
    ]
